# Generated by Django 4.2.14 on 2024-08-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0007_alter_area_text'),
        ('accounts', '0004_alter_customuser_school_delete_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='better_buildings.school'),
        ),
    ]
