# Generated by Django 5.0.7 on 2024-07-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue_Type',
            new_name='IssueType',
        ),
    ]
