# Generated by Django 5.0.6 on 2024-08-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0002_announcementseen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementSeen',
        ),
    ]
