# Generated by Django 5.0.7 on 2024-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0002_rename_issue_type_issuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='text',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
