# Generated by Django 5.0.6 on 2024-08-18 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0003_delete_announcementseen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
