# Generated by Django 5.0.7 on 2024-07-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0003_alter_issuetype_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueType',
            new_name='Area',
        ),
    ]
