# Generated by Django 5.0.6 on 2024-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0004_announcement_seen_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.CharField(max_length=45, unique=True)),
            ],
        ),
    ]
