# Generated by Django 5.0.7 on 2024-07-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0004_rename_issuetype_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='issue_type',
            new_name='area',
        ),
    ]
