# Generated by Django 5.0.6 on 2024-08-23 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0005_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='better_buildings.school'),
        ),
        migrations.AddField(
            model_name='area',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='better_buildings.school'),
        ),
        migrations.AddField(
            model_name='report',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='better_buildings.school'),
        ),
    ]
