# Generated by Django 4.2.14 on 2024-08-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0006_report_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
