# Generated by Django 5.0.6 on 2024-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0006_announcement_school_area_school_report_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
