# Generated by Django 4.2.14 on 2024-08-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0007_report_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
