# Generated by Django 4.2.14 on 2024-08-03 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('better_buildings', '0010_remove_report_upvotes_report_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='users_upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
