# Generated by Django 5.0.7 on 2024-08-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0013_bugreport_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
