# Generated by Django 5.0.6 on 2024-08-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0015_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
