# Generated by Django 5.0.6 on 2024-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0016_announcement_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
