# Generated by Django 5.0.6 on 2024-08-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0017_announcement_resolved_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='users_upvoted',
        ),
    ]
