# Generated by Django 5.0.6 on 2024-08-10 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0018_remove_report_users_upvoted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
