# Generated by Django 5.0.6 on 2024-08-11 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_buildings', '0021_alter_report_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='better_buildings.area'),
        ),
    ]
